package(default_visibility = ["//visibility:private"])

cc_library(
    name = "v16",
    srcs = [
    ],
    hdrs = [
        "debug_helper.h",
        "node.h",
        "ph_entry.h",
        "ph_iterator_base.h",
        "ph_iterator_full.h",
        "ph_iterator_hc.h",
        "ph_iterator_knn_hs.h",
        "ph_iterator_simple.h",
        "phtree_v16.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//phtree/common",
    ],
)
