package(default_visibility = ["//visibility:private"])

cc_library(
    name = "gtest_main",
    testonly = True,
    srcs = ["gtest_main.cc"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@gtest",
    ],
    alwayslink = 1,
)
