package(default_visibility = ["//visibility:private"])

cc_library(
    name = "common",
    hdrs = [
        "base_types.h",
        "bits.h",
        "common.h",
        "converter.h",
        "debug_helper.h",
        "distance.h",
        "filter.h",
        "flat_array_map.h",
        "b_plus_tree_hash_map.h",
        "b_plus_tree_map.h",
        "flat_sparse_map.h",
        "tree_stats.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
    ],
)
